<?php
/**
 * GetCharactersCharacterIdStatsTravel
 *
 * PHP version 5
 *
 * @category Class
 * @package  nullx27ESI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace nullx27ESI\nullx27\ESI\Models;

use \ArrayAccess;
use \nullx27ESI\ObjectSerializer;

/**
 * GetCharactersCharacterIdStatsTravel Class Doc Comment
 *
 * @category Class
 * @description travel object
 * @package  nullx27ESI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GetCharactersCharacterIdStatsTravel implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'get_characters_character_id_stats_travel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'accelerationGateActivations' => 'int',
        'alignTo' => 'int',
        'distanceWarpedHighSec' => 'int',
        'distanceWarpedLowSec' => 'int',
        'distanceWarpedNullSec' => 'int',
        'distanceWarpedWormhole' => 'int',
        'docksHighSec' => 'int',
        'docksLowSec' => 'int',
        'docksNullSec' => 'int',
        'jumpsStargateHighSec' => 'int',
        'jumpsStargateLowSec' => 'int',
        'jumpsStargateNullSec' => 'int',
        'jumpsWormhole' => 'int',
        'warpsHighSec' => 'int',
        'warpsLowSec' => 'int',
        'warpsNullSec' => 'int',
        'warpsToBookmark' => 'int',
        'warpsToCelestial' => 'int',
        'warpsToFleetMember' => 'int',
        'warpsToScanResult' => 'int',
        'warpsWormhole' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'accelerationGateActivations' => 'int64',
        'alignTo' => 'int64',
        'distanceWarpedHighSec' => 'int64',
        'distanceWarpedLowSec' => 'int64',
        'distanceWarpedNullSec' => 'int64',
        'distanceWarpedWormhole' => 'int64',
        'docksHighSec' => 'int64',
        'docksLowSec' => 'int64',
        'docksNullSec' => 'int64',
        'jumpsStargateHighSec' => 'int64',
        'jumpsStargateLowSec' => 'int64',
        'jumpsStargateNullSec' => 'int64',
        'jumpsWormhole' => 'int64',
        'warpsHighSec' => 'int64',
        'warpsLowSec' => 'int64',
        'warpsNullSec' => 'int64',
        'warpsToBookmark' => 'int64',
        'warpsToCelestial' => 'int64',
        'warpsToFleetMember' => 'int64',
        'warpsToScanResult' => 'int64',
        'warpsWormhole' => 'int64'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'accelerationGateActivations' => 'acceleration_gate_activations',
        'alignTo' => 'align_to',
        'distanceWarpedHighSec' => 'distance_warped_high_sec',
        'distanceWarpedLowSec' => 'distance_warped_low_sec',
        'distanceWarpedNullSec' => 'distance_warped_null_sec',
        'distanceWarpedWormhole' => 'distance_warped_wormhole',
        'docksHighSec' => 'docks_high_sec',
        'docksLowSec' => 'docks_low_sec',
        'docksNullSec' => 'docks_null_sec',
        'jumpsStargateHighSec' => 'jumps_stargate_high_sec',
        'jumpsStargateLowSec' => 'jumps_stargate_low_sec',
        'jumpsStargateNullSec' => 'jumps_stargate_null_sec',
        'jumpsWormhole' => 'jumps_wormhole',
        'warpsHighSec' => 'warps_high_sec',
        'warpsLowSec' => 'warps_low_sec',
        'warpsNullSec' => 'warps_null_sec',
        'warpsToBookmark' => 'warps_to_bookmark',
        'warpsToCelestial' => 'warps_to_celestial',
        'warpsToFleetMember' => 'warps_to_fleet_member',
        'warpsToScanResult' => 'warps_to_scan_result',
        'warpsWormhole' => 'warps_wormhole'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'accelerationGateActivations' => 'setAccelerationGateActivations',
        'alignTo' => 'setAlignTo',
        'distanceWarpedHighSec' => 'setDistanceWarpedHighSec',
        'distanceWarpedLowSec' => 'setDistanceWarpedLowSec',
        'distanceWarpedNullSec' => 'setDistanceWarpedNullSec',
        'distanceWarpedWormhole' => 'setDistanceWarpedWormhole',
        'docksHighSec' => 'setDocksHighSec',
        'docksLowSec' => 'setDocksLowSec',
        'docksNullSec' => 'setDocksNullSec',
        'jumpsStargateHighSec' => 'setJumpsStargateHighSec',
        'jumpsStargateLowSec' => 'setJumpsStargateLowSec',
        'jumpsStargateNullSec' => 'setJumpsStargateNullSec',
        'jumpsWormhole' => 'setJumpsWormhole',
        'warpsHighSec' => 'setWarpsHighSec',
        'warpsLowSec' => 'setWarpsLowSec',
        'warpsNullSec' => 'setWarpsNullSec',
        'warpsToBookmark' => 'setWarpsToBookmark',
        'warpsToCelestial' => 'setWarpsToCelestial',
        'warpsToFleetMember' => 'setWarpsToFleetMember',
        'warpsToScanResult' => 'setWarpsToScanResult',
        'warpsWormhole' => 'setWarpsWormhole'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'accelerationGateActivations' => 'getAccelerationGateActivations',
        'alignTo' => 'getAlignTo',
        'distanceWarpedHighSec' => 'getDistanceWarpedHighSec',
        'distanceWarpedLowSec' => 'getDistanceWarpedLowSec',
        'distanceWarpedNullSec' => 'getDistanceWarpedNullSec',
        'distanceWarpedWormhole' => 'getDistanceWarpedWormhole',
        'docksHighSec' => 'getDocksHighSec',
        'docksLowSec' => 'getDocksLowSec',
        'docksNullSec' => 'getDocksNullSec',
        'jumpsStargateHighSec' => 'getJumpsStargateHighSec',
        'jumpsStargateLowSec' => 'getJumpsStargateLowSec',
        'jumpsStargateNullSec' => 'getJumpsStargateNullSec',
        'jumpsWormhole' => 'getJumpsWormhole',
        'warpsHighSec' => 'getWarpsHighSec',
        'warpsLowSec' => 'getWarpsLowSec',
        'warpsNullSec' => 'getWarpsNullSec',
        'warpsToBookmark' => 'getWarpsToBookmark',
        'warpsToCelestial' => 'getWarpsToCelestial',
        'warpsToFleetMember' => 'getWarpsToFleetMember',
        'warpsToScanResult' => 'getWarpsToScanResult',
        'warpsWormhole' => 'getWarpsWormhole'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['accelerationGateActivations'] = isset($data['accelerationGateActivations']) ? $data['accelerationGateActivations'] : null;
        $this->container['alignTo'] = isset($data['alignTo']) ? $data['alignTo'] : null;
        $this->container['distanceWarpedHighSec'] = isset($data['distanceWarpedHighSec']) ? $data['distanceWarpedHighSec'] : null;
        $this->container['distanceWarpedLowSec'] = isset($data['distanceWarpedLowSec']) ? $data['distanceWarpedLowSec'] : null;
        $this->container['distanceWarpedNullSec'] = isset($data['distanceWarpedNullSec']) ? $data['distanceWarpedNullSec'] : null;
        $this->container['distanceWarpedWormhole'] = isset($data['distanceWarpedWormhole']) ? $data['distanceWarpedWormhole'] : null;
        $this->container['docksHighSec'] = isset($data['docksHighSec']) ? $data['docksHighSec'] : null;
        $this->container['docksLowSec'] = isset($data['docksLowSec']) ? $data['docksLowSec'] : null;
        $this->container['docksNullSec'] = isset($data['docksNullSec']) ? $data['docksNullSec'] : null;
        $this->container['jumpsStargateHighSec'] = isset($data['jumpsStargateHighSec']) ? $data['jumpsStargateHighSec'] : null;
        $this->container['jumpsStargateLowSec'] = isset($data['jumpsStargateLowSec']) ? $data['jumpsStargateLowSec'] : null;
        $this->container['jumpsStargateNullSec'] = isset($data['jumpsStargateNullSec']) ? $data['jumpsStargateNullSec'] : null;
        $this->container['jumpsWormhole'] = isset($data['jumpsWormhole']) ? $data['jumpsWormhole'] : null;
        $this->container['warpsHighSec'] = isset($data['warpsHighSec']) ? $data['warpsHighSec'] : null;
        $this->container['warpsLowSec'] = isset($data['warpsLowSec']) ? $data['warpsLowSec'] : null;
        $this->container['warpsNullSec'] = isset($data['warpsNullSec']) ? $data['warpsNullSec'] : null;
        $this->container['warpsToBookmark'] = isset($data['warpsToBookmark']) ? $data['warpsToBookmark'] : null;
        $this->container['warpsToCelestial'] = isset($data['warpsToCelestial']) ? $data['warpsToCelestial'] : null;
        $this->container['warpsToFleetMember'] = isset($data['warpsToFleetMember']) ? $data['warpsToFleetMember'] : null;
        $this->container['warpsToScanResult'] = isset($data['warpsToScanResult']) ? $data['warpsToScanResult'] : null;
        $this->container['warpsWormhole'] = isset($data['warpsWormhole']) ? $data['warpsWormhole'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets accelerationGateActivations
     *
     * @return int
     */
    public function getAccelerationGateActivations()
    {
        return $this->container['accelerationGateActivations'];
    }

    /**
     * Sets accelerationGateActivations
     *
     * @param int $accelerationGateActivations acceleration_gate_activations integer
     *
     * @return $this
     */
    public function setAccelerationGateActivations($accelerationGateActivations)
    {
        $this->container['accelerationGateActivations'] = $accelerationGateActivations;

        return $this;
    }

    /**
     * Gets alignTo
     *
     * @return int
     */
    public function getAlignTo()
    {
        return $this->container['alignTo'];
    }

    /**
     * Sets alignTo
     *
     * @param int $alignTo align_to integer
     *
     * @return $this
     */
    public function setAlignTo($alignTo)
    {
        $this->container['alignTo'] = $alignTo;

        return $this;
    }

    /**
     * Gets distanceWarpedHighSec
     *
     * @return int
     */
    public function getDistanceWarpedHighSec()
    {
        return $this->container['distanceWarpedHighSec'];
    }

    /**
     * Sets distanceWarpedHighSec
     *
     * @param int $distanceWarpedHighSec distance_warped_high_sec integer
     *
     * @return $this
     */
    public function setDistanceWarpedHighSec($distanceWarpedHighSec)
    {
        $this->container['distanceWarpedHighSec'] = $distanceWarpedHighSec;

        return $this;
    }

    /**
     * Gets distanceWarpedLowSec
     *
     * @return int
     */
    public function getDistanceWarpedLowSec()
    {
        return $this->container['distanceWarpedLowSec'];
    }

    /**
     * Sets distanceWarpedLowSec
     *
     * @param int $distanceWarpedLowSec distance_warped_low_sec integer
     *
     * @return $this
     */
    public function setDistanceWarpedLowSec($distanceWarpedLowSec)
    {
        $this->container['distanceWarpedLowSec'] = $distanceWarpedLowSec;

        return $this;
    }

    /**
     * Gets distanceWarpedNullSec
     *
     * @return int
     */
    public function getDistanceWarpedNullSec()
    {
        return $this->container['distanceWarpedNullSec'];
    }

    /**
     * Sets distanceWarpedNullSec
     *
     * @param int $distanceWarpedNullSec distance_warped_null_sec integer
     *
     * @return $this
     */
    public function setDistanceWarpedNullSec($distanceWarpedNullSec)
    {
        $this->container['distanceWarpedNullSec'] = $distanceWarpedNullSec;

        return $this;
    }

    /**
     * Gets distanceWarpedWormhole
     *
     * @return int
     */
    public function getDistanceWarpedWormhole()
    {
        return $this->container['distanceWarpedWormhole'];
    }

    /**
     * Sets distanceWarpedWormhole
     *
     * @param int $distanceWarpedWormhole distance_warped_wormhole integer
     *
     * @return $this
     */
    public function setDistanceWarpedWormhole($distanceWarpedWormhole)
    {
        $this->container['distanceWarpedWormhole'] = $distanceWarpedWormhole;

        return $this;
    }

    /**
     * Gets docksHighSec
     *
     * @return int
     */
    public function getDocksHighSec()
    {
        return $this->container['docksHighSec'];
    }

    /**
     * Sets docksHighSec
     *
     * @param int $docksHighSec docks_high_sec integer
     *
     * @return $this
     */
    public function setDocksHighSec($docksHighSec)
    {
        $this->container['docksHighSec'] = $docksHighSec;

        return $this;
    }

    /**
     * Gets docksLowSec
     *
     * @return int
     */
    public function getDocksLowSec()
    {
        return $this->container['docksLowSec'];
    }

    /**
     * Sets docksLowSec
     *
     * @param int $docksLowSec docks_low_sec integer
     *
     * @return $this
     */
    public function setDocksLowSec($docksLowSec)
    {
        $this->container['docksLowSec'] = $docksLowSec;

        return $this;
    }

    /**
     * Gets docksNullSec
     *
     * @return int
     */
    public function getDocksNullSec()
    {
        return $this->container['docksNullSec'];
    }

    /**
     * Sets docksNullSec
     *
     * @param int $docksNullSec docks_null_sec integer
     *
     * @return $this
     */
    public function setDocksNullSec($docksNullSec)
    {
        $this->container['docksNullSec'] = $docksNullSec;

        return $this;
    }

    /**
     * Gets jumpsStargateHighSec
     *
     * @return int
     */
    public function getJumpsStargateHighSec()
    {
        return $this->container['jumpsStargateHighSec'];
    }

    /**
     * Sets jumpsStargateHighSec
     *
     * @param int $jumpsStargateHighSec jumps_stargate_high_sec integer
     *
     * @return $this
     */
    public function setJumpsStargateHighSec($jumpsStargateHighSec)
    {
        $this->container['jumpsStargateHighSec'] = $jumpsStargateHighSec;

        return $this;
    }

    /**
     * Gets jumpsStargateLowSec
     *
     * @return int
     */
    public function getJumpsStargateLowSec()
    {
        return $this->container['jumpsStargateLowSec'];
    }

    /**
     * Sets jumpsStargateLowSec
     *
     * @param int $jumpsStargateLowSec jumps_stargate_low_sec integer
     *
     * @return $this
     */
    public function setJumpsStargateLowSec($jumpsStargateLowSec)
    {
        $this->container['jumpsStargateLowSec'] = $jumpsStargateLowSec;

        return $this;
    }

    /**
     * Gets jumpsStargateNullSec
     *
     * @return int
     */
    public function getJumpsStargateNullSec()
    {
        return $this->container['jumpsStargateNullSec'];
    }

    /**
     * Sets jumpsStargateNullSec
     *
     * @param int $jumpsStargateNullSec jumps_stargate_null_sec integer
     *
     * @return $this
     */
    public function setJumpsStargateNullSec($jumpsStargateNullSec)
    {
        $this->container['jumpsStargateNullSec'] = $jumpsStargateNullSec;

        return $this;
    }

    /**
     * Gets jumpsWormhole
     *
     * @return int
     */
    public function getJumpsWormhole()
    {
        return $this->container['jumpsWormhole'];
    }

    /**
     * Sets jumpsWormhole
     *
     * @param int $jumpsWormhole jumps_wormhole integer
     *
     * @return $this
     */
    public function setJumpsWormhole($jumpsWormhole)
    {
        $this->container['jumpsWormhole'] = $jumpsWormhole;

        return $this;
    }

    /**
     * Gets warpsHighSec
     *
     * @return int
     */
    public function getWarpsHighSec()
    {
        return $this->container['warpsHighSec'];
    }

    /**
     * Sets warpsHighSec
     *
     * @param int $warpsHighSec warps_high_sec integer
     *
     * @return $this
     */
    public function setWarpsHighSec($warpsHighSec)
    {
        $this->container['warpsHighSec'] = $warpsHighSec;

        return $this;
    }

    /**
     * Gets warpsLowSec
     *
     * @return int
     */
    public function getWarpsLowSec()
    {
        return $this->container['warpsLowSec'];
    }

    /**
     * Sets warpsLowSec
     *
     * @param int $warpsLowSec warps_low_sec integer
     *
     * @return $this
     */
    public function setWarpsLowSec($warpsLowSec)
    {
        $this->container['warpsLowSec'] = $warpsLowSec;

        return $this;
    }

    /**
     * Gets warpsNullSec
     *
     * @return int
     */
    public function getWarpsNullSec()
    {
        return $this->container['warpsNullSec'];
    }

    /**
     * Sets warpsNullSec
     *
     * @param int $warpsNullSec warps_null_sec integer
     *
     * @return $this
     */
    public function setWarpsNullSec($warpsNullSec)
    {
        $this->container['warpsNullSec'] = $warpsNullSec;

        return $this;
    }

    /**
     * Gets warpsToBookmark
     *
     * @return int
     */
    public function getWarpsToBookmark()
    {
        return $this->container['warpsToBookmark'];
    }

    /**
     * Sets warpsToBookmark
     *
     * @param int $warpsToBookmark warps_to_bookmark integer
     *
     * @return $this
     */
    public function setWarpsToBookmark($warpsToBookmark)
    {
        $this->container['warpsToBookmark'] = $warpsToBookmark;

        return $this;
    }

    /**
     * Gets warpsToCelestial
     *
     * @return int
     */
    public function getWarpsToCelestial()
    {
        return $this->container['warpsToCelestial'];
    }

    /**
     * Sets warpsToCelestial
     *
     * @param int $warpsToCelestial warps_to_celestial integer
     *
     * @return $this
     */
    public function setWarpsToCelestial($warpsToCelestial)
    {
        $this->container['warpsToCelestial'] = $warpsToCelestial;

        return $this;
    }

    /**
     * Gets warpsToFleetMember
     *
     * @return int
     */
    public function getWarpsToFleetMember()
    {
        return $this->container['warpsToFleetMember'];
    }

    /**
     * Sets warpsToFleetMember
     *
     * @param int $warpsToFleetMember warps_to_fleet_member integer
     *
     * @return $this
     */
    public function setWarpsToFleetMember($warpsToFleetMember)
    {
        $this->container['warpsToFleetMember'] = $warpsToFleetMember;

        return $this;
    }

    /**
     * Gets warpsToScanResult
     *
     * @return int
     */
    public function getWarpsToScanResult()
    {
        return $this->container['warpsToScanResult'];
    }

    /**
     * Sets warpsToScanResult
     *
     * @param int $warpsToScanResult warps_to_scan_result integer
     *
     * @return $this
     */
    public function setWarpsToScanResult($warpsToScanResult)
    {
        $this->container['warpsToScanResult'] = $warpsToScanResult;

        return $this;
    }

    /**
     * Gets warpsWormhole
     *
     * @return int
     */
    public function getWarpsWormhole()
    {
        return $this->container['warpsWormhole'];
    }

    /**
     * Sets warpsWormhole
     *
     * @param int $warpsWormhole warps_wormhole integer
     *
     * @return $this
     */
    public function setWarpsWormhole($warpsWormhole)
    {
        $this->container['warpsWormhole'] = $warpsWormhole;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


