<?php
/**
 * GetCharactersCharacterIdPlanetsPlanetIdLink
 *
 * PHP version 5
 *
 * @category Class
 * @package  nullx27ESI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace nullx27ESI\nullx27\ESI\Models;

use \ArrayAccess;
use \nullx27ESI\ObjectSerializer;

/**
 * GetCharactersCharacterIdPlanetsPlanetIdLink Class Doc Comment
 *
 * @category Class
 * @description link object
 * @package  nullx27ESI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GetCharactersCharacterIdPlanetsPlanetIdLink implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'get_characters_character_id_planets_planet_id_link';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'sourcePinId' => 'int',
        'destinationPinId' => 'int',
        'linkLevel' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'sourcePinId' => 'int64',
        'destinationPinId' => 'int64',
        'linkLevel' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sourcePinId' => 'source_pin_id',
        'destinationPinId' => 'destination_pin_id',
        'linkLevel' => 'link_level'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sourcePinId' => 'setSourcePinId',
        'destinationPinId' => 'setDestinationPinId',
        'linkLevel' => 'setLinkLevel'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sourcePinId' => 'getSourcePinId',
        'destinationPinId' => 'getDestinationPinId',
        'linkLevel' => 'getLinkLevel'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['sourcePinId'] = isset($data['sourcePinId']) ? $data['sourcePinId'] : null;
        $this->container['destinationPinId'] = isset($data['destinationPinId']) ? $data['destinationPinId'] : null;
        $this->container['linkLevel'] = isset($data['linkLevel']) ? $data['linkLevel'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['sourcePinId'] === null) {
            $invalidProperties[] = "'sourcePinId' can't be null";
        }
        if ($this->container['destinationPinId'] === null) {
            $invalidProperties[] = "'destinationPinId' can't be null";
        }
        if ($this->container['linkLevel'] === null) {
            $invalidProperties[] = "'linkLevel' can't be null";
        }
        if (($this->container['linkLevel'] > 10)) {
            $invalidProperties[] = "invalid value for 'linkLevel', must be smaller than or equal to 10.";
        }

        if (($this->container['linkLevel'] < 0)) {
            $invalidProperties[] = "invalid value for 'linkLevel', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['sourcePinId'] === null) {
            return false;
        }
        if ($this->container['destinationPinId'] === null) {
            return false;
        }
        if ($this->container['linkLevel'] === null) {
            return false;
        }
        if ($this->container['linkLevel'] > 10) {
            return false;
        }
        if ($this->container['linkLevel'] < 0) {
            return false;
        }
        return true;
    }


    /**
     * Gets sourcePinId
     *
     * @return int
     */
    public function getSourcePinId()
    {
        return $this->container['sourcePinId'];
    }

    /**
     * Sets sourcePinId
     *
     * @param int $sourcePinId source_pin_id integer
     *
     * @return $this
     */
    public function setSourcePinId($sourcePinId)
    {
        $this->container['sourcePinId'] = $sourcePinId;

        return $this;
    }

    /**
     * Gets destinationPinId
     *
     * @return int
     */
    public function getDestinationPinId()
    {
        return $this->container['destinationPinId'];
    }

    /**
     * Sets destinationPinId
     *
     * @param int $destinationPinId destination_pin_id integer
     *
     * @return $this
     */
    public function setDestinationPinId($destinationPinId)
    {
        $this->container['destinationPinId'] = $destinationPinId;

        return $this;
    }

    /**
     * Gets linkLevel
     *
     * @return int
     */
    public function getLinkLevel()
    {
        return $this->container['linkLevel'];
    }

    /**
     * Sets linkLevel
     *
     * @param int $linkLevel link_level integer
     *
     * @return $this
     */
    public function setLinkLevel($linkLevel)
    {

        if (($linkLevel > 10)) {
            throw new \InvalidArgumentException('invalid value for $linkLevel when calling GetCharactersCharacterIdPlanetsPlanetIdLink., must be smaller than or equal to 10.');
        }
        if (($linkLevel < 0)) {
            throw new \InvalidArgumentException('invalid value for $linkLevel when calling GetCharactersCharacterIdPlanetsPlanetIdLink., must be bigger than or equal to 0.');
        }

        $this->container['linkLevel'] = $linkLevel;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


