<?php
/**
 * GetCharactersCharacterIdNotificationsContacts200Ok
 *
 * PHP version 5
 *
 * @category Class
 * @package  nullx27\ESI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace nullx27\ESI\nullx27\ESI\Models;

use \ArrayAccess;
use \nullx27\ESI\ObjectSerializer;

/**
 * GetCharactersCharacterIdNotificationsContacts200Ok Class Doc Comment
 *
 * @category Class
 * @description 200 ok object
 * @package  nullx27\ESI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GetCharactersCharacterIdNotificationsContacts200Ok implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'get_characters_character_id_notifications_contacts_200_ok';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'notificationId' => 'int',
        'sendDate' => '\DateTime',
        'standingLevel' => 'float',
        'message' => 'string',
        'senderCharacterId' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'notificationId' => 'int32',
        'sendDate' => 'date-time',
        'standingLevel' => 'float',
        'message' => null,
        'senderCharacterId' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'notificationId' => 'notification_id',
        'sendDate' => 'send_date',
        'standingLevel' => 'standing_level',
        'message' => 'message',
        'senderCharacterId' => 'sender_character_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'notificationId' => 'setNotificationId',
        'sendDate' => 'setSendDate',
        'standingLevel' => 'setStandingLevel',
        'message' => 'setMessage',
        'senderCharacterId' => 'setSenderCharacterId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'notificationId' => 'getNotificationId',
        'sendDate' => 'getSendDate',
        'standingLevel' => 'getStandingLevel',
        'message' => 'getMessage',
        'senderCharacterId' => 'getSenderCharacterId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['notificationId'] = isset($data['notificationId']) ? $data['notificationId'] : null;
        $this->container['sendDate'] = isset($data['sendDate']) ? $data['sendDate'] : null;
        $this->container['standingLevel'] = isset($data['standingLevel']) ? $data['standingLevel'] : null;
        $this->container['message'] = isset($data['message']) ? $data['message'] : null;
        $this->container['senderCharacterId'] = isset($data['senderCharacterId']) ? $data['senderCharacterId'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['notificationId'] === null) {
            $invalidProperties[] = "'notificationId' can't be null";
        }
        if ($this->container['sendDate'] === null) {
            $invalidProperties[] = "'sendDate' can't be null";
        }
        if ($this->container['standingLevel'] === null) {
            $invalidProperties[] = "'standingLevel' can't be null";
        }
        if ($this->container['message'] === null) {
            $invalidProperties[] = "'message' can't be null";
        }
        if ($this->container['senderCharacterId'] === null) {
            $invalidProperties[] = "'senderCharacterId' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['notificationId'] === null) {
            return false;
        }
        if ($this->container['sendDate'] === null) {
            return false;
        }
        if ($this->container['standingLevel'] === null) {
            return false;
        }
        if ($this->container['message'] === null) {
            return false;
        }
        if ($this->container['senderCharacterId'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets notificationId
     *
     * @return int
     */
    public function getNotificationId()
    {
        return $this->container['notificationId'];
    }

    /**
     * Sets notificationId
     *
     * @param int $notificationId notification_id integer
     *
     * @return $this
     */
    public function setNotificationId($notificationId)
    {
        $this->container['notificationId'] = $notificationId;

        return $this;
    }

    /**
     * Gets sendDate
     *
     * @return \DateTime
     */
    public function getSendDate()
    {
        return $this->container['sendDate'];
    }

    /**
     * Sets sendDate
     *
     * @param \DateTime $sendDate send_date string
     *
     * @return $this
     */
    public function setSendDate($sendDate)
    {
        $this->container['sendDate'] = $sendDate;

        return $this;
    }

    /**
     * Gets standingLevel
     *
     * @return float
     */
    public function getStandingLevel()
    {
        return $this->container['standingLevel'];
    }

    /**
     * Sets standingLevel
     *
     * @param float $standingLevel A number representing the standing level the receiver has been added at by the sender. The standing levels are as follows: -10 -> Terrible | -5 -> Bad |  0 -> Neutral |  5 -> Good |  10 -> Excellent
     *
     * @return $this
     */
    public function setStandingLevel($standingLevel)
    {
        $this->container['standingLevel'] = $standingLevel;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string $message message string
     *
     * @return $this
     */
    public function setMessage($message)
    {
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets senderCharacterId
     *
     * @return int
     */
    public function getSenderCharacterId()
    {
        return $this->container['senderCharacterId'];
    }

    /**
     * Sets senderCharacterId
     *
     * @param int $senderCharacterId sender_character_id integer
     *
     * @return $this
     */
    public function setSenderCharacterId($senderCharacterId)
    {
        $this->container['senderCharacterId'] = $senderCharacterId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


