<?php
/**
 * GetCharactersCharacterIdPlanetsPlanetIdPinTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  nullx27\ESI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2.dev16
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace nullx27\ESI;

/**
 * GetCharactersCharacterIdPlanetsPlanetIdPinTest Class Doc Comment
 *
 * @category    Class */
// * @description pin object
/**
 * @package     nullx27\ESI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetCharactersCharacterIdPlanetsPlanetIdPinTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GetCharactersCharacterIdPlanetsPlanetIdPin"
     */
    public function testGetCharactersCharacterIdPlanetsPlanetIdPin()
    {

    }

    /**
     * Test attribute "expiryTime"
     */
    public function testPropertyExpiryTime()
    {

    }

    /**
     * Test attribute "extractorDetails"
     */
    public function testPropertyExtractorDetails()
    {

    }

    /**
     * Test attribute "factoryDetails"
     */
    public function testPropertyFactoryDetails()
    {

    }

    /**
     * Test attribute "installTime"
     */
    public function testPropertyInstallTime()
    {

    }

    /**
     * Test attribute "lastCycleStart"
     */
    public function testPropertyLastCycleStart()
    {

    }

    /**
     * Test attribute "latitude"
     */
    public function testPropertyLatitude()
    {

    }

    /**
     * Test attribute "longitude"
     */
    public function testPropertyLongitude()
    {

    }

    /**
     * Test attribute "pinId"
     */
    public function testPropertyPinId()
    {

    }

    /**
     * Test attribute "schematicId"
     */
    public function testPropertySchematicId()
    {

    }

    /**
     * Test attribute "typeId"
     */
    public function testPropertyTypeId()
    {

    }

}
