<?php
/**
 * GetCharactersCharacterIdAgentsResearch200OkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  nullx27\ESI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace nullx27\ESI;

/**
 * GetCharactersCharacterIdAgentsResearch200OkTest Class Doc Comment
 *
 * @category    Class */
// * @description 200 ok object
/**
 * @package     nullx27\ESI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetCharactersCharacterIdAgentsResearch200OkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GetCharactersCharacterIdAgentsResearch200Ok"
     */
    public function testGetCharactersCharacterIdAgentsResearch200Ok()
    {

    }

    /**
     * Test attribute "agentId"
     */
    public function testPropertyAgentId()
    {

    }

    /**
     * Test attribute "pointsPerDay"
     */
    public function testPropertyPointsPerDay()
    {

    }

    /**
     * Test attribute "remainderPoints"
     */
    public function testPropertyRemainderPoints()
    {

    }

    /**
     * Test attribute "skillTypeId"
     */
    public function testPropertySkillTypeId()
    {

    }

    /**
     * Test attribute "startedAt"
     */
    public function testPropertyStartedAt()
    {

    }

}
