<?php
/**
 * GetDogmaEffectsEffectIdOkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  nullx27\ESI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2.dev16
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace nullx27\ESI;

/**
 * GetDogmaEffectsEffectIdOkTest Class Doc Comment
 *
 * @category    Class */
// * @description 200 ok object
/**
 * @package     nullx27\ESI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetDogmaEffectsEffectIdOkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GetDogmaEffectsEffectIdOk"
     */
    public function testGetDogmaEffectsEffectIdOk()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "disallowAutoRepeat"
     */
    public function testPropertyDisallowAutoRepeat()
    {

    }

    /**
     * Test attribute "dischargeAttributeId"
     */
    public function testPropertyDischargeAttributeId()
    {

    }

    /**
     * Test attribute "displayName"
     */
    public function testPropertyDisplayName()
    {

    }

    /**
     * Test attribute "durationAttributeId"
     */
    public function testPropertyDurationAttributeId()
    {

    }

    /**
     * Test attribute "effectCategory"
     */
    public function testPropertyEffectCategory()
    {

    }

    /**
     * Test attribute "effectId"
     */
    public function testPropertyEffectId()
    {

    }

    /**
     * Test attribute "electronicChance"
     */
    public function testPropertyElectronicChance()
    {

    }

    /**
     * Test attribute "falloffAttributeId"
     */
    public function testPropertyFalloffAttributeId()
    {

    }

    /**
     * Test attribute "iconId"
     */
    public function testPropertyIconId()
    {

    }

    /**
     * Test attribute "isAssistance"
     */
    public function testPropertyIsAssistance()
    {

    }

    /**
     * Test attribute "isOffensive"
     */
    public function testPropertyIsOffensive()
    {

    }

    /**
     * Test attribute "isWarpSafe"
     */
    public function testPropertyIsWarpSafe()
    {

    }

    /**
     * Test attribute "modifiers"
     */
    public function testPropertyModifiers()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "postExpression"
     */
    public function testPropertyPostExpression()
    {

    }

    /**
     * Test attribute "preExpression"
     */
    public function testPropertyPreExpression()
    {

    }

    /**
     * Test attribute "published"
     */
    public function testPropertyPublished()
    {

    }

    /**
     * Test attribute "rangeAttributeId"
     */
    public function testPropertyRangeAttributeId()
    {

    }

    /**
     * Test attribute "rangeChance"
     */
    public function testPropertyRangeChance()
    {

    }

    /**
     * Test attribute "trackingSpeedAttributeId"
     */
    public function testPropertyTrackingSpeedAttributeId()
    {

    }

}
