<?php
/**
 * GetCharactersCharacterIdPlanets200Ok
 *
 * PHP version 5
 *
 * @category Class
 * @package  nullx27\ESI
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.9.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace nullx27\ESI\Models;

use \ArrayAccess;

/**
 * GetCharactersCharacterIdPlanets200Ok Class Doc Comment
 *
 * @category    Class */
 // @description 200 ok object
/**
 * @package     nullx27\ESI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetCharactersCharacterIdPlanets200Ok implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'get_characters_character_id_planets_200_ok';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'lastUpdate' => '\DateTime',
        'numPins' => 'int',
        'ownerId' => 'int',
        'planetId' => 'int',
        'planetType' => 'string',
        'solarSystemId' => 'int',
        'upgradeLevel' => 'int'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'lastUpdate' => 'last_update',
        'numPins' => 'num_pins',
        'ownerId' => 'owner_id',
        'planetId' => 'planet_id',
        'planetType' => 'planet_type',
        'solarSystemId' => 'solar_system_id',
        'upgradeLevel' => 'upgrade_level'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'lastUpdate' => 'setLastUpdate',
        'numPins' => 'setNumPins',
        'ownerId' => 'setOwnerId',
        'planetId' => 'setPlanetId',
        'planetType' => 'setPlanetType',
        'solarSystemId' => 'setSolarSystemId',
        'upgradeLevel' => 'setUpgradeLevel'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'lastUpdate' => 'getLastUpdate',
        'numPins' => 'getNumPins',
        'ownerId' => 'getOwnerId',
        'planetId' => 'getPlanetId',
        'planetType' => 'getPlanetType',
        'solarSystemId' => 'getSolarSystemId',
        'upgradeLevel' => 'getUpgradeLevel'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const PLANET_TYPE_TEMPERATE = 'temperate';
    const PLANET_TYPE_BARREN = 'barren';
    const PLANET_TYPE_OCEANIC = 'oceanic';
    const PLANET_TYPE_ICE = 'ice';
    const PLANET_TYPE_GAS = 'gas';
    const PLANET_TYPE_LAVA = 'lava';
    const PLANET_TYPE_STORM = 'storm';
    const PLANET_TYPE_PLASMA = 'plasma';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getPlanetTypeAllowableValues()
    {
        return [
            self::PLANET_TYPE_TEMPERATE,
            self::PLANET_TYPE_BARREN,
            self::PLANET_TYPE_OCEANIC,
            self::PLANET_TYPE_ICE,
            self::PLANET_TYPE_GAS,
            self::PLANET_TYPE_LAVA,
            self::PLANET_TYPE_STORM,
            self::PLANET_TYPE_PLASMA,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['lastUpdate'] = isset($data['lastUpdate']) ? $data['lastUpdate'] : null;
        $this->container['numPins'] = isset($data['numPins']) ? $data['numPins'] : null;
        $this->container['ownerId'] = isset($data['ownerId']) ? $data['ownerId'] : null;
        $this->container['planetId'] = isset($data['planetId']) ? $data['planetId'] : null;
        $this->container['planetType'] = isset($data['planetType']) ? $data['planetType'] : null;
        $this->container['solarSystemId'] = isset($data['solarSystemId']) ? $data['solarSystemId'] : null;
        $this->container['upgradeLevel'] = isset($data['upgradeLevel']) ? $data['upgradeLevel'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        if ($this->container['lastUpdate'] === null) {
            $invalid_properties[] = "'lastUpdate' can't be null";
        }
        if ($this->container['numPins'] === null) {
            $invalid_properties[] = "'numPins' can't be null";
        }
        if (($this->container['numPins'] < 1)) {
            $invalid_properties[] = "invalid value for 'numPins', must be bigger than or equal to 1.";
        }

        if ($this->container['ownerId'] === null) {
            $invalid_properties[] = "'ownerId' can't be null";
        }
        if ($this->container['planetId'] === null) {
            $invalid_properties[] = "'planetId' can't be null";
        }
        if ($this->container['planetType'] === null) {
            $invalid_properties[] = "'planetType' can't be null";
        }
        $allowed_values = ["temperate", "barren", "oceanic", "ice", "gas", "lava", "storm", "plasma"];
        if (!in_array($this->container['planetType'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'planetType', must be one of #{allowed_values}.";
        }

        if ($this->container['solarSystemId'] === null) {
            $invalid_properties[] = "'solarSystemId' can't be null";
        }
        if ($this->container['upgradeLevel'] === null) {
            $invalid_properties[] = "'upgradeLevel' can't be null";
        }
        if (($this->container['upgradeLevel'] > 5)) {
            $invalid_properties[] = "invalid value for 'upgradeLevel', must be smaller than or equal to 5.";
        }

        if (($this->container['upgradeLevel'] < 0)) {
            $invalid_properties[] = "invalid value for 'upgradeLevel', must be bigger than or equal to 0.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['lastUpdate'] === null) {
            return false;
        }
        if ($this->container['numPins'] === null) {
            return false;
        }
        if ($this->container['numPins'] < 1) {
            return false;
        }
        if ($this->container['ownerId'] === null) {
            return false;
        }
        if ($this->container['planetId'] === null) {
            return false;
        }
        if ($this->container['planetType'] === null) {
            return false;
        }
        $allowed_values = ["temperate", "barren", "oceanic", "ice", "gas", "lava", "storm", "plasma"];
        if (!in_array($this->container['planetType'], $allowed_values)) {
            return false;
        }
        if ($this->container['solarSystemId'] === null) {
            return false;
        }
        if ($this->container['upgradeLevel'] === null) {
            return false;
        }
        if ($this->container['upgradeLevel'] > 5) {
            return false;
        }
        if ($this->container['upgradeLevel'] < 0) {
            return false;
        }
        return true;
    }


    /**
     * Gets lastUpdate
     * @return \DateTime
     */
    public function getLastUpdate()
    {
        return $this->container['lastUpdate'];
    }

    /**
     * Sets lastUpdate
     * @param \DateTime $lastUpdate last_update string
     * @return $this
     */
    public function setLastUpdate($lastUpdate)
    {
        $this->container['lastUpdate'] = $lastUpdate;

        return $this;
    }

    /**
     * Gets numPins
     * @return int
     */
    public function getNumPins()
    {
        return $this->container['numPins'];
    }

    /**
     * Sets numPins
     * @param int $numPins num_pins integer
     * @return $this
     */
    public function setNumPins($numPins)
    {

        if (($numPins < 1)) {
            throw new \InvalidArgumentException('invalid value for $numPins when calling GetCharactersCharacterIdPlanets200Ok., must be bigger than or equal to 1.');
        }

        $this->container['numPins'] = $numPins;

        return $this;
    }

    /**
     * Gets ownerId
     * @return int
     */
    public function getOwnerId()
    {
        return $this->container['ownerId'];
    }

    /**
     * Sets ownerId
     * @param int $ownerId owner_id integer
     * @return $this
     */
    public function setOwnerId($ownerId)
    {
        $this->container['ownerId'] = $ownerId;

        return $this;
    }

    /**
     * Gets planetId
     * @return int
     */
    public function getPlanetId()
    {
        return $this->container['planetId'];
    }

    /**
     * Sets planetId
     * @param int $planetId planet_id integer
     * @return $this
     */
    public function setPlanetId($planetId)
    {
        $this->container['planetId'] = $planetId;

        return $this;
    }

    /**
     * Gets planetType
     * @return string
     */
    public function getPlanetType()
    {
        return $this->container['planetType'];
    }

    /**
     * Sets planetType
     * @param string $planetType planet_type string
     * @return $this
     */
    public function setPlanetType($planetType)
    {
        $allowed_values = array('temperate', 'barren', 'oceanic', 'ice', 'gas', 'lava', 'storm', 'plasma');
        if ((!in_array($planetType, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'planetType', must be one of 'temperate', 'barren', 'oceanic', 'ice', 'gas', 'lava', 'storm', 'plasma'");
        }
        $this->container['planetType'] = $planetType;

        return $this;
    }

    /**
     * Gets solarSystemId
     * @return int
     */
    public function getSolarSystemId()
    {
        return $this->container['solarSystemId'];
    }

    /**
     * Sets solarSystemId
     * @param int $solarSystemId solar_system_id integer
     * @return $this
     */
    public function setSolarSystemId($solarSystemId)
    {
        $this->container['solarSystemId'] = $solarSystemId;

        return $this;
    }

    /**
     * Gets upgradeLevel
     * @return int
     */
    public function getUpgradeLevel()
    {
        return $this->container['upgradeLevel'];
    }

    /**
     * Sets upgradeLevel
     * @param int $upgradeLevel upgrade_level integer
     * @return $this
     */
    public function setUpgradeLevel($upgradeLevel)
    {

        if (($upgradeLevel > 5)) {
            throw new \InvalidArgumentException('invalid value for $upgradeLevel when calling GetCharactersCharacterIdPlanets200Ok., must be smaller than or equal to 5.');
        }
        if (($upgradeLevel < 0)) {
            throw new \InvalidArgumentException('invalid value for $upgradeLevel when calling GetCharactersCharacterIdPlanets200Ok., must be bigger than or equal to 0.');
        }

        $this->container['upgradeLevel'] = $upgradeLevel;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\nullx27\ESI\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\nullx27\ESI\ObjectSerializer::sanitizeForSerialization($this));
    }
}


